spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa
    driver-class-name: org.h2.Driver
  data:
    rest:
      base-path: /api
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    show-sql: false
auto-diagnosis:
  quartz-property-file: config/quartz.properties
